#Hilton Truong 1615505 assignment 3
a3w22:
	g++ -std=c++11 -Wall a3w22.cpp master.cpp master.h switch.cpp switch.h general.cpp general.h -o a3w22

tar:
	tar -cvf submit.tar makefile a3w22.cpp master.cpp master.h switch.cpp switch.h general.cpp general.h 379Report3.pdf
	gzip submit.tar

clean:
	rm -f *~ out.* *.o 